postgresql:
  enabled: false
  mode: external
  external:
    host: postgres.example.internal
    port: 5432
    database: kubecert
    existingSecret: kubecert-postgresql

redis:
  enabled: false
  mode: external
  external:
    host: redis.example.internal
    port: 6379
    existingSecret: kubecert-redis

keda:
  mode: external
kedaOperator:
  enabled: false
