postgresql:
  enabled: false
  mode: external
  external:
    host: postgres.example.internal
    port: 5432
    database: kubecert
    existingSecret: kubecert-postgresql
  auth:
    existingSecret: kubecert-postgresql
    username: kubecert
    database: kubecert
    passwordKey: password

redis:
  enabled: false
  mode: external
  external:
    host: redis.example.internal
    port: 6379
    existingSecret: kubecert-redis
  auth:
    existingSecret: kubecert-redis
    passwordKey: password

keda:
  mode: external
kedaOperator:
  enabled: false
