apiVersion: v2
name: kubecert
description: Helm chart for the Kubecert exam platform
type: application
version: 0.1.12
appVersion: "v1.0.0-20260529.r1"
home: https://github.com/Hoony-Song/kubecert-chart
sources:
  - https://github.com/Hoony-Song/kubecert-chart
keywords:
  - kubernetes
  - certification
  - exam
  - cka
  - ckad
  - cks
maintainers:
  - name: Hoony-Song
dependencies:
  - name: postgresql
    version: 18.6.7
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 25.5.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: keda
    alias: kedaOperator
    version: 2.19.0
    repository: https://kedacore.github.io/charts
    condition: kedaOperator.enabled
